// Generated by CoffeeScript 1.6.3
var APIKEY, Calendar, checkAuth, clientId, handleAuthClick, handleAuthResult, handleClientLoad, scopes;

APIKEY = 'AIzaSyDf_29T5PvBnRAc3iqkzHXo_MnxwN17-GU';

scopes = ['https://www.googleapis.com/auth/calendar'];

clientId = '17929449522-pgng8h8l7qp3h8adpnn5rb4il5v7nsb5.apps.googleusercontent.com';

handleClientLoad = function() {
  gapi.client.setApiKey(APIKEY);
  return window.setTimeout(function() {
    return checkAuth(handleAuthResult, 1);
  });
};

checkAuth = function(onResult) {
  return gapi.auth.authorize({
    client_id: clientId,
    scope: scopes,
    immediate: true
  }, onResult);
};

handleAuthResult = function(authResult) {
  var authorizeButton;
  authorizeButton = document.getElementById('authorize-button');
  if (authResult && !authResult.error) {
    return authorizeButton.style.visibility = 'hidden';
  } else {
    authorizeButton.style.visibility = '';
    return authorizeButton.onclick = handleAuthClick;
  }
};

handleAuthClick = function(event) {
  gapi.auth.authorize({
    client_id: clientId,
    scope: scopes,
    immediate: false
  }, handleAuthResult);
  return false;
};

Calendar = (function() {
  function Calendar(username, password) {
    this.username = username;
    this.password = password;
  }

  Calendar.prototype.add = function(message, minutes) {
    var cal, path, text;
    cal = 'cm.eriksen@gmail.com';
    path = "https://www.googleapis.com/calendar/v3/calendars/" + cal + "/events?pp=1&key=" + APIKEY;
    text = 'Brunch with Mom at Java 11am Sunday';
    message = text;
    return $.post(path, {
      'text': message
    }, function(data) {
      return $('body').append("Successfully posted to the page.");
    });
  };

  Calendar.prototype.addTwo = function(message, minutes) {
    var end, start;
    start = new Date();
    start.setMinutes(start.getMinutes() + minutes);
    end = new Date();
    end.setMinutes(end.getMinutes() + minutes);
    return gapi.client.load('calendar', 'v3', function() {
      var request, resource;
      resource = {
        "summary": message,
        "location": "Somewhere",
        "start": {
          "dateTime": start.toISOString()
        },
        "end": {
          "dateTime": end.toISOString()
        }
      };
      request = gapi.client.calendar.events.insert({
        'calendarId': 'primary',
        'resource': resource
      });
      return request.execute(function(resp) {
        return console.log(resp);
      });
    });
  };

  return Calendar;

})();
