// Generated by CoffeeScript 1.6.3
$(function() {
  var calendar, submitButton;
  calendar = new Calendar('test', 'fest');
  submitButton = $('#submit');
  submitButton.click(function() {
    return calendar.add($('#todotext').val(), parseInt($('#minutes').val()), function() {
      var alert;
      alert = $('.alert-success');
      alert.show();
      return setTimeout(function() {
        return alert.hide();
      }, 1000);
    });
  });
  $('#todotext').focus();
  return $('.alert .close').click(function() {
    return $(this).parent().hide();
  });
});
