// Generated by CoffeeScript 1.6.3
$(function() {
  var calendar, submitButton;
  calendar = new Calendar('test', 'fest');
  submitButton = $('#submit');
  submitButton.click(function() {
    return calendar.addTwo($('#todotext').val(), parseInt($('#minutes').val()));
  });
  return $('#todotext').focus();
});
