// Generated by CoffeeScript 1.6.3
var _this = this;

test('hello world', function() {
  return ok(1 === 1);
});

test('calendar_can_be_initialized', function() {
  var calendar;
  calendar = new Calendar('martinmedmitten', 'password');
  return ok(true, "did not crash");
});

asyncTest('authorize_works', function() {
  return checkAuth(function(authResult) {
    ok(!authResult.error);
    return start();
  });
});

test('calendar_add_makes', function() {
  var calendar, minutes;
  calendar = new Calendar('martinmedmitten', 'password');
  minutes = 60;
  return calendar.add('message', minutes);
});
